//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpireUniversity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allocate
    {
        public int Id { get; set; }
        public string Department { get; set; }
        public string Course { get; set; }
        public string RoomNo { get; set; }
        public string Day { get; set; }
        public string FromTime { get; set; }
        public string ToTime { get; set; }
        public string FromTimeHH { get; set; }
        public string FromTimeMM { get; set; }
        public string ToTimeHH { get; set; }
        public string ToTimeMM { get; set; }
        public string FromTimeAMPM { get; set; }
        public string ToTimeAMPM { get; set; }
    }
}
