//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Data.Entity;

namespace EmpireUniversity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public int DepartmentID { get; set; }
       [Required]

       //[Index("DepartmentCode", 1, IsUnique = true)]
        public int DepartmentCode { get; set; }
        public string DepartmentName { get; set; }
    }
}
