//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace EmpireUniversity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {

    [Required]
        public int TeacherID { get; set; }

    [Required]
        public string TeacherName { get; set; }

    [Required]
        public string TeacherAddress { get; set; }

    [Required]
        [DataType(DataType.EmailAddress, ErrorMessage = "E-mail is not valid")]
        public string TeacherEmail { get; set; }

    [Required]
    [Range(11, 11)]
        public string TeacherPhoneNo { get; set; }

    [Required]
        public int CreditTaken { get; set; }

    [Required]
        public string Designation { get; set; }

    [Required]
        public string Department { get; set; }
    }
}
